version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
      - target:/app/target
volumes:
  node_modules: {}
  target: {}
