FROM node:14.4.0

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PROJECT_ROOTDIR /app/

WORKDIR $PROJECT_ROOTDIR

# COPY package*.json  $PROJECT_ROOTDIR

# RUN npm install

ENV HOST 0.0.0.0

CMD ["/usr/bin/env", "bash"]
